---
name: AR-ar-dashboard Actions
#on: [push, workflow_dispatch]
on:
  pull_request:
    types:
      - closed
env:
  AWS_REGION: us-east-1
permissions:
  contents: write
jobs:
  If_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: >
          echo The PR was merged # Print a message if the pull request was merged
          
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
